### ISSUE TITLE
Emulator always shows all joysticks as connected

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#85] opened 2023-04-09 17:37 UTC
Pretty sure its a known issue, but there isn't an open one here.

**Comment by mooinglemur** [comment] 2023-04-10 04:16
I believe this was a ROM issue closed by https://github.com/X16Community/x16-rom/pull/77

Cannot reproduce with a current ROM/emu combo.

![image](https://user-images.githubusercontent.com/395186/230824771-8834692e-ecf4-4161-9f02-b4d47cd8eb97.png)

**Closed by mooinglemur** 2023-04-10 04:16 UTC
